# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:5000/sign
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


{
"username":"test",
"nickname":"test",
"password":"test",
"mailbox":"test@mail.com"
}

###
POST http://localhost:5000/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


{
"username":"test",
"password":"test"
}

###
POST http://localhost:5000/create_room
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzA5NTY3OTMsImlhdCI6MTU3MDk0OTU5MywiaWQiOjEsInVzZXJuYW1lIjoidGVzdCIsImF1dGgiOiJVU0VSIiwiaXAiOiIxMjcuMC4wLjEifQ.7jnIjPw2ddQciUucTZ_PML7El-1KfsTX9ZbxjSH9k3o;

{
  "room_name":"test",
  "description":"test",
  "auth_need": "None"
}

###
POST http://localhost:5000/room/test
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Cookie: token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NzA5NTA3ODIsImlhdCI6MTU3MDk0MzU4MiwiaWQiOjEsInVzZXJuYW1lIjoidGVzdCIsImF1dGgiOiJVU0VSIiwiaXAiOiIxMjcuMC4wLjEifQ.usF4xy5UtWuj3c4O5cIEyc1q8C9IQLIAyd8SKMwV4pg;


###
